import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import ClientLayout from "./client-layout";
import FogCursor from "@/app/components/FogCursor";


const MokotoDemo = localFont({
  src: [{ path: "../../public/fonts/MokotoDemo.ttf", weight: "400", style: "normal" }],
  variable: "--font-mokoto",
  display: "swap",
});

const MortendBold = localFont({
  src: [{ path: "../../public/fonts/MortendBold.ttf", weight: "700", style: "normal" }],
  variable: "--font-mortend",
  display: "swap",
});

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Roborashtra 2K26",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${MokotoDemo.variable} ${MortendBold.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="antialiased">
        <FogCursor />
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
