import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Frame from "./components/frame";
import PageReloader from "./components/PageReloader";
import FloatingParticles from "./components/FloatingParticles";

const MokotoDemo = localFont({
  src: [
    { path: '../../public/fonts/MokotoDemo.ttf', weight: '400', style: 'normal' },
  ],
  variable: '--font-mokoto',   // optional: CSS variable name
  display: 'swap',             // recommended
})

const MortendBold = localFont({
  src: [
    { path: '../../public/fonts/MortendBold.ttf', weight: '700', style: 'normal' },
  ],
  variable: '--font-mortend',
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Roborashtra 2K26",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${MokotoDemo.variable} ${MortendBold.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Frame />

        {/* Floating Circuit Elements */}
        <div className="absolute w-full h-screen overflow-hidden">
          <FloatingParticles count={20} color="#0a91ab" size={7} className="opacity-30" />
        </div>

        <main className="relative overflow-hidden">
          <PageReloader>{children}</PageReloader>
        </main>
      </body>
    </html>
  );
}
