import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const MokotoDemo = localFont({
  src: [
    { path: '../../public/fonts/MokotoDemo.ttf', weight: '400', style: 'normal' },
  ],
  variable: '--font-mokoto',   // optional: CSS variable name
  display: 'swap',             // recommended
})

const MortendBold = localFont({
  src: [
    { path: '../../public/fonts/MortendBold.ttf', weight: '700', style: 'normal' },
  ],
  variable: '--font-mortend',
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${MokotoDemo.variable} ${MortendBold.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
